### ISSUE TITLE
Improve inc and dec commands

### ISSUE THREAD

**Issue by alexkubica** [ryukinix/mal#16]
I think that inc or dec commands should get the number of episodes to change as an argument, for exmaple:

```
mal inc Naruto 5
```

Instead of increasing/decreasing one episode at a time.

**Comment by ryukinix** [comment]
Well, if we can implement this with the condition of `mal inc <anime>` still do the same for now I'm ok with it. How about add a flag like `-n 5`? E.g: `mal inc Naruto -n 5`. For default -n will be 1 for inc and -1 for dec.

**Comment by alexkubica** [comment]
Yes, it can be done that the number argument is optional and if none is given it will default to one.

**Comment by alexkubica** [comment]
I'm closing the issue since #26 has been merged, thanks!

**Comment by ryukinix** [comment]
Just a note: the actual implementation is really the initial description that you made here. 

![image](https://cloud.githubusercontent.com/assets/7642878/21967650/d9c64560-db69-11e6-9ceb-7f789bbec043.png)

The default defined by one don't works because the argument is positional. You think is ok that way or is better something like `mal lion inc -n 2` and for default `n=1`? Would be great retro-compatibility with the old one `mal inc lion`.
