### ISSUE TITLE
Adding support to manga list

### ISSUE THREAD

**Issue by alexkubica** [ryukinix/mal#41]
I think it's time to add a upport to do actions on the manga list (inc/dec/search, etc.).
It might be as easier as replacing API urls' `anime` word to `manga`, be we need to check if the XML results match in format.
We could add an argument `--mode` which could either get anime or manga, when the default is anime.

**Comment by xxami** [comment]
i'm working on this atm, have got it listing, needs some work on search/update/stats, probably going to be a bit ugly at first due to mapping through types all over the place, but hopefully that can be fixed later. going to ignore volumes for now, since i only care about chapters, and that's conveniently synonymous with episodes :P

**Comment by ryukinix** [comment]
Thanks for contributing on it @xxami

**Comment by ryukinix** [comment]
@xxami how the manga support is going?

**Comment by ryukinix** [comment]
@xxami are you there? xD

`ping  @xxami`

**Comment by xxami** [comment]
hey, sorry! i did technically do this on a branch in my fork https://github.com/xxami/mal/commits/feature/support-for-manga
but i didn't share it back because i don't think it was very nicely done, i wanted to rewrite it again with some kind of abstraction for anime/manga models, but i haven't got round to it T___T

**Comment by ryukinix** [comment]
This is completely ok! Thank you for all this works so far. Since we 
have not well planed how long will takes to create a good 
implementation for the manga support, I'm delaying the integration of 
anime support from v0.4 to any further version.

When you have some time and news about it, please ping us on this. Take 
your time.

Be welcome.
-- 
As lembranças não são só do passado. Podem ser de agora e até de 
amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação,
Universidade Federal do Ceará.

**Comment by alexkubica** [comment]
@xxami Would you like to open a PR for a review?

**Comment by alexkubica** [comment]
I'm closing this since it's been a while and I want to cleanup my issues inbox :)
