### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by alexkubica** [ryukinix/mal#6]
Hello I have version 2.11.1 of requests installed and mal complains when running, it gives this output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 861, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.11.1 (/usr/lib/python3.5/site-packages), Requirement.parse('requests==2.10.0'), {'mal'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mal", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 677, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.10.0' distribution was not found and is required by mal
```

Could you update the dependencies please? Thank you.

**Comment by ryukinix** [comment]
Of course! I'll update in soon and update on PyPI. I think I has a new version of MAL on development, so I'll put the next version with updated requirements.

**Comment by alexkubica** [comment]
Thanks that's great!
I think you should use minimum versions instead of exact ones, for example:

```
decorating>=0.3
```

This way you could still use older versions and also newer ones won't break the program.
Also I have noticed that you haven't mentioned `decorating` and `appdirs` in the requirements in README, is there a reason for that?

**Comment by ryukinix** [comment]
Yes. appdirs was included in the next version that I'm working (not published yet on PyPI) and [decorating](www.github.com/ryukinix/decorating) did born based in this initial project.

I need put that information in README.md in soon, but i'm without time to work in some things of that project for now, as you see in the issues still opened (mostly new features).

About minimal versions I don't know if is really a good idea because can break the package itself without we know the guilty. I prefer update the requirements manually when be necessary and when the new update don't works more I can update the mal package abou this specific problem.

**Comment by alexkubica** [comment]
I see, do you plan on releasing the new version when you finish solving the issues?
I'd love to help if you want.
I'm closing this issue BTW.

**Comment by ryukinix** [comment]
Yes, I'm trying merge the #7 to master to put the `v0.1.5` on PyPI and solve the problem with legacy dependencies. BTW, the decorating was using the v0.3 when the last release is v0.5.

Would really great some help in this project. I need update the README.md, create docs using readthedocs (sphinx), refactoring again the CLI architecture to get a better user experience for the nest commands (avoiding the mess of `- x- q- w- e- r-r` from GNU and BSD unix tools when is possible) and implement the new features slowly. 

I wanna the most simple syntax for cli possible, because the GUI of mal is already mess, I don't want the same thing here hahaha.

**Comment by alexkubica** [comment]
I'll try my best to help!

**Comment by alexkubica** [comment]
Could you open issues for all the things you said in the last comment?

**Comment by ryukinix** [comment]
Of course. I'll do that.

**Comment by ryukinix** [comment]
#8 
#9 
#10
