### ISSUE TITLE
Abandon appdirs and use ~/.config/mal

### ISSUE THREAD

**Issue by kutsan** [ryukinix/mal#94]
I understand your trouble to use `appdirs`' `user_config_dir` function to get proper config directory but in mac side for a command-line application putting configuration files under`~/Library/Application Support/mal` does not make sense at all. It's there mostly for GUI apps. `mal` should use `~/.config/mal/` as default nomatter what.

Can't say anything about Windows though but AFAIK it should be `C:\Users\<username>\mal\myanimelist.ini`.

Apart from that, I have set `$XDG_CONFIG_HOME`, why don't you use that? (Although, it's a Linux standard, it's still acceptable under Unix as far as I see.) I think you should drop support for `appdirs` and use common config paths or `$XDG_CONFIG_HOME` if they are set.

**Comment by ryukinix** [comment]
Yeah, less dependencies, this makes me happy. I'll plan something to do that. But I'll not lookup for env-vars anyway, from my experience this really better and cross-platform:

```python
from os.path import expanduser
home = expanduser("~")
```

**Comment by kutsan** [comment]
I'm okay with that but -just saying- you probably should obey the XDG spec.

**Comment by ryukinix** [comment]
Thanks, but I pass.
![screenshot_2018-03-19_07-12-40](https://user-images.githubusercontent.com/7642878/37589799-2ce59756-2b5e-11e8-85a0-2792dd94099c.png)

**Comment by kutsan** [comment]
Oh, I see.

**Comment by ryukinix** [comment]
I'll only take serious this thread if we'll focus on title literally, otherwise, appdirs. Why removing appdirs because your use-case it's broken to adding more complexity of Win/Mac/Linux? If we would do that, should literally that: `~/.config/mal` (makes more sense on Linux) or `~/.mal` (makes more sense on any system).

**Comment by ryukinix** [comment]
> Oh, I see.

It's a joke, but the last comment it's true. A lot of users here are really thinking about feature stuff, standards, even fucking semantic-versioning on development level. But who are thinking about maintaining code as well simplicity of it? I don't see anyone doing that, actually I don't see anyone doing almost anything about the code beyond just complain stuff that doesn't works how someone like or is not made it how someone would do it -- which is pretty common thing on open source community, moreover I even don't know why I'm saying something so obvious. 

The last threads and comments on the repo... was such a disaster. But, anyway, removing appdirs it's a good thing. I'll look into that later.

**Comment by kutsan** [comment]
I'm not sure I understand correctly but isn't it how it supposed to be? Users want features and they don't care anything beyond features? I understand you've been running free and open-source software, want some appreciation beyond complains but what do you expect? Even if they all complain, it's still the fact they spend their time to give feedbacks.

**Comment by ryukinix** [comment]
Appreciation it's not important. Collaboration it's important. If we just take this philosophy above, all of our software will written the way as PHP, systemd or GNU software is written. Well... but what I'm saying, who cares about writing great software.

It's github after all.

**Comment by bradenbest** [comment]
@ryukinix 

I do care about writing great software and code quality, to an obsessive degree. I just dislike dealing with python and all the egg shit, is all, so I know I'd have to put extra time into learning that stuff just to be able to test a build. If I had more personal time and more patience, I might fork the project and add some of the features we've discussed. I might even refactor a lot of the code to OCD levels of simplicity.

You seem jaded, though. Maybe you should take a break. `mal` is fine as it is, it works. Features like torrent browsing and manga list can wait. Take a break, focus on the bugs and project-level stuff like unit tests and the installation process (for example, the installation is DOA on systems that have both python2 and 3, as I notice some of the files just specify "python" instead of "python3", which on systems like mine, evals to python2 and causes a crash. Every time I did a clean install I had to edit some file to change `/usr/bin/env python` to `/usr/bin/env python3`), and then tackle the features when the base is nice and solid.

Maybe my method of collaboration (giving ideas and dumping loads of information in attempt to help out without actually contributing any code) isn't ideal, but at least I'm trying to do more than be a leech.

**Comment by kutsan** [comment]
@ryukinix I also do care about writing great software; I also don't like neither PHP, systemd nor GNU's code but I do not think they are bad because they haven't got enough collaboration, but some other reasons. Your project is still fresh from the oven, give some time to it and I believe by time of progress you'll reach to your goals.

> If we just take this philosophy above

My philosophy was; just a chill a little, listen your users, bear with them. If they like you, someone eventually will give some useful feedbacks. In conclusion, we are all here, spending time for you to how to make `mal` better.
