### ISSUE TITLE
[Feature Request] List related anime in extended info

### ISSUE THREAD

**Issue by bradenbest** [ryukinix/mal#98]
One of the main reasons I have to keep coming back to the website after starting/finishing a single entry, is to check the related anime to see if there's an OVA, movie, or sequel to be seen. It would be nice to have this information available when I `search`, `list` or `filter` an anime with `--extend`.

Do you think a feature like this would be possible given MAL's API?

**Comment by ryukinix** [comment]
> Do you think a feature like this would be possible given MAL's API?

No. There is no such entry about that on mal API documentation. You can just look the output by itself on Python REPL exploring the `mal.api` of this repository or looking at the official docs of mal.

BTW, take a look here in this AWESOME and great API of MAL features: https://myanimelist.net/modules.php?go=api

Since, I didn't have interest to use web-scraping stuff and there is no such thing on mal API, there is no reason to keep this issue open.

This feature indeed is a good thing, I would wish we can do it. But beyond the constraints I assume, this will not be implemented here.

If you wish adding web scraping stuff, would be nice see your experiment being happy at mal scrapping. But, as I described in another threads, I don't have interest to merge this type of feature. Features it's great, but software working as promised is more important. Adding web scrapping at mal for me it's just a way to sell your soul for the devil.

I think that it's all.

**Comment by kutsan** [comment]
Better should someone write a MAL Python library with web scraping stuff. I bet it would be better than official API. xD
